INSERT INTO citta (IDCitta, Nome, Regione) VALUES (-1, 'Online', 'N/A');
INSERT INTO citta (Nome, Regione) VALUES ('Roma', 'Lazio');
INSERT INTO citta (Nome, Regione) VALUES ('Milano', 'Lombardia');
INSERT INTO citta (Nome, Regione) VALUES ('Napoli', 'Campania');
INSERT INTO citta (Nome, Regione) VALUES ('Torino', 'Piemonte');
INSERT INTO citta (Nome, Regione) VALUES ('Palermo', 'Sicilia');
INSERT INTO citta (Nome, Regione) VALUES ('Genova', 'Liguria');
INSERT INTO citta (Nome, Regione) VALUES ('Bologna', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Firenze', 'Toscana');
INSERT INTO citta (Nome, Regione) VALUES ('Bari', 'Puglia');
INSERT INTO citta (Nome, Regione) VALUES ('Catania', 'Sicilia');
INSERT INTO citta (Nome, Regione) VALUES ('Venezia', 'Veneto');
INSERT INTO citta (Nome, Regione) VALUES ('Verona', 'Veneto');
INSERT INTO citta (Nome, Regione) VALUES ('Messina', 'Sicilia');
INSERT INTO citta (Nome, Regione) VALUES ('Padova', 'Veneto');
INSERT INTO citta (Nome, Regione) VALUES ('Trieste', 'Friuli-Venezia Giulia');
INSERT INTO citta (Nome, Regione) VALUES ('Taranto', 'Puglia');
INSERT INTO citta (Nome, Regione) VALUES ('Brescia', 'Lombardia');
INSERT INTO citta (Nome, Regione) VALUES ('Parma', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Prato', 'Toscana');
INSERT INTO citta (Nome, Regione) VALUES ('Modena', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Reggio Calabria', 'Calabria');
INSERT INTO citta (Nome, Regione) VALUES ('Reggio Emilia', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Perugia', 'Umbria');
INSERT INTO citta (Nome, Regione) VALUES ('Livorno', 'Toscana');
INSERT INTO citta (Nome, Regione) VALUES ('Ravenna', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Cagliari', 'Sardegna');
INSERT INTO citta (Nome, Regione) VALUES ('Foggia', 'Puglia');
INSERT INTO citta (Nome, Regione) VALUES ('Rimini', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Salerno', 'Campania');
INSERT INTO citta (Nome, Regione) VALUES ('Ferrara', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Sassari', 'Sardegna');
INSERT INTO citta (Nome, Regione) VALUES ('Latina', 'Lazio');
INSERT INTO citta (Nome, Regione) VALUES ('Giugliano in Campania', 'Campania');
INSERT INTO citta (Nome, Regione) VALUES ('Monza', 'Lombardia');
INSERT INTO citta (Nome, Regione) VALUES ('Siracusa', 'Sicilia');
INSERT INTO citta (Nome, Regione) VALUES ('Pescara', 'Abruzzo');
INSERT INTO citta (Nome, Regione) VALUES ('Bergamo', 'Lombardia');
INSERT INTO citta (Nome, Regione) VALUES ('Forlì', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Trento', 'Trentino-Alto Adige');
INSERT INTO citta (Nome, Regione) VALUES ('Vicenza', 'Veneto');
INSERT INTO citta (Nome, Regione) VALUES ('Terni', 'Umbria');
INSERT INTO citta (Nome, Regione) VALUES ('Bolzano', 'Trentino-Alto Adige');
INSERT INTO citta (Nome, Regione) VALUES ('Novara', 'Piemonte');
INSERT INTO citta (Nome, Regione) VALUES ('Piacenza', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Ancona', 'Marche');
INSERT INTO citta (Nome, Regione) VALUES ('Andria', 'Puglia');
INSERT INTO citta (Nome, Regione) VALUES ('Arezzo', 'Toscana');
INSERT INTO citta (Nome, Regione) VALUES ('Udine', 'Friuli-Venezia Giulia');
INSERT INTO citta (Nome, Regione) VALUES ('Cesena', 'Emilia-Romagna');
INSERT INTO citta (Nome, Regione) VALUES ('Lecce', 'Puglia');
