INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Successo estesa background', 'Salerno, Strada Nina, 20', '200', 'Stesso sinistro studiare tedesco caldo giudizio. Grazie andare ufficiale servire. Toccare raggiungere giovane. Mancare permettere giallo fatica.', '2024-11-07', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Conoscenza base reattiva ottimizzante', 'Trento, Canale Dario, 124 Piano 3', '250', 'Ferro poeta freddo entrare piantare. Metro generale automobile forma regno usare mi. Porta amore ministro richiedere morale.', '2024-01-07', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Adattatore gestita euristica', 'Brescia, Contrada Gianna, 72 Appartamento 7', '150', 'Suonare oramai processo chiaro pomeriggio fornire.
Crisi bambino giovanotto ritenere. Occasione ridere sposare accettare dente governo.', '2024-03-05', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Firmware riallineata statica', 'http://www.franscini-franscini.com/', '-1', 'Li sacro opinione situazione memoria aspettare dinanzi. Corrente fianco assumere sforzo arte albero giallo.
Destino noi gioia società. Cioè avvenire segretario.', '2024-03-21', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Metodologia avanzata non-volatile', 'Trieste, Piazza Ruggero, 34 Piano 5', '300', 'Buio sguardo strumento personaggio segretario giro. Minuto qualcuno esame offendere macchina. Rispetto intenzione movimento oh importare.', '2024-10-09', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Adattatore versatile sistematica', 'Reggio Emilia, Via Antonia, 373 Appartamento 2', '50', 'Fermo bellezza signora che vita. Cioè elemento dedicare occhio. Interno attento qualche soldato. Lungo americano cane giornale gioco.', '2024-06-05', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Sito web integrata biforcata', 'Bolzano, Piazza Giammusso, 4', '250', 'Governo appartenere creare. Scrittore infine ci capire riconoscere speranza. Solito labbro bastare permettere sorgere simile ammazzare.', '2024-05-02', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura multi-canale basata sul contenuto', 'Cagliari, Canale Puccio, 15', '-1', 'Uno vestire circa sala. Procedere tono magari neppure grosso passione. Sorella mattino rendere preparare giocare accendere.', '2024-07-18', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('framework intuitiva alto livello', 'Foggia, Rotonda Agostino, 56', '-1', 'Tentare erba linea. Luce pieno sicuro grande bello intanto.
Giorno italiano simile. Numero campagna massimo sera attorno. Inizio sicuro misura tornare.', '2024-07-09', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Core configurabile olistica', 'https://www.filangieri.org/', '-1', 'Iniziare operazione genere potenza rapporto no perfetto quello. Relazione solo gettare impedire.', '2024-06-14', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Hardware condivisibile terza generazione', 'https://www.spinola.com/', '-1', 'Piangere contro lettera come viso caso. Tutto nazionale zitto temere magari. Sviluppo orecchio testa assai arrestare mentre o.', '2024-08-09', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Adattatore multi-canale alto livello', 'http://ceschi.com/', '-1', 'Unire azzurro largo caffè stato esprimere parete. Personaggio figlio pubblico pace.', '2024-05-11', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Progetto open-source radicale', 'http://www.villadicani.net/', '-1', 'Cane vestire inoltre personaggio cavallo. Grigio giungere caffè piazza guerra. Età essa mercato forma zona. Stamattina attorno nascondere industriale persona egli gatto.', '2024-10-17', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Matrici distribuita valore aggiunto', 'http://www.rossellini.it/', '-1', 'Assoluto stato sì famiglia aiuto appena persona distruggere. Aumentare preciso giugno nazione pezzo. Vi interno poeta chiave troppo. Possibile malattia stesso futuro vostro notte nave.', '2024-07-21', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura intuitiva 24 ore', 'http://lettiere-maspero.eu/', '-1', 'Mantenere sorprendere temere superare figura chiamare felice. Cortile militare appoggiare scappare uomo pace.', '2024-04-10', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Sinergia distribuita multi-tasking', 'http://saffi.it/', '-1', 'Umano salutare bastare considerare costa vicino attore. Permettere intenzione visita largo loro. Dolore forma modo ah successo chi.', '2024-07-19', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Set di istruzioni ottimizzata full-range', 'Rimini, Contrada Sergius, 172 Appartamento 41', '250', 'Grande ragazza celebrare caffè fondare memoria. Intanto relazione gioco colpa rapido.', '2024-10-26', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Struttura avanzata logistica', 'http://www.merisi.net/', '-1', 'Troppo migliore giardino corsa soluzione termine. Cane fenomeno valere.
Giustizia persona crisi pietà.', '2024-08-06', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Concetto programmabile nazionale', 'https://www.romano.com/', '-1', 'Entro stampa fatica professore nome moderno un morte.
Programma carne nudo arrestare caso. Fra sedere potenza desiderare usare coprire.', '2024-04-24', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Concetto organica mission-critical', 'https://www.antonini-interiano.it/', '-1', 'Abitare sostenere rientrare vivo. Fabbrica stamattina giovanotto funzione neanche forte contento.', '2024-03-23', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Analizzatore visionaria basta sul contesto', 'http://prodi.it/', '-1', 'Attenzione solito fronte enorme cominciare istante spegnere. Appena speciale baciare enorme.', '2024-01-10', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Intelligenza artificiale inversa omogenea', 'https://www.orengo-babati.eu/', '-1', 'Passato base avvocato. Attaccare richiedere produrre affatto perché.
Scrittore esperienza aspettare significare. Passare oramai scappare concetto ah resistere.', '2024-05-25', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Strumenti integrata multimedia', 'Udine, Incrocio Marino, 52', '250', 'Sopra autore centrale perfino processo. Richiedere bestia colpa preoccupare immaginare immagine ufficiale proporre.', '2024-11-05', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Struttura di prezzo assimilata alto livello', 'Forlì, Borgo Tarantino, 620', '200', 'Cattivo terzo natura settimana. Esame dopo pronto fratello.
Anzi visita forse. Limitare viaggio partecipare film sembrare.', '2024-11-08', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Implementazione reattiva modulare', 'https://olivetti.it/', '-1', 'Alcuno centro giovane duro. Attenzione fine epoca anzi. Estate paura accendere largo.
Mantenere erba assai studio. Poiché seguito prima inutile rispondere segreto.', '2024-08-17', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Matrici riallineata uniforme', 'http://www.montanari.net/', '-1', 'Domanda nave magari iniziare rientrare colpire nome pericoloso. Riconoscere nessuno passato braccio molto nascere. Natura fiducia significare segretario.', '2024-07-04', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Adattatore configurabile dedicata', 'Napoli, Stretto Vergerio, 73 Appartamento 69', '-1', 'Prossimo capitare rendere immaginare ambiente scherzare qualunque credere. Capire prova misura oltre.
Crescere durare capo sembrare limite tempo niente. Libro accordo loro risultare volta badare.', '2024-05-17', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Standardizzazione assimilata nextgeneration', 'Pescara, Rotonda Massimiliano, 513', '250', 'Tirare contrario studiare. Animo costituire festa dividere. Centrale tendere chiaro bene don comunque.
Coscienza parete luogo estero controllo soprattutto. Povero tu ragazza poeta battaglia.', '2024-05-31', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Gerarchia ottimizzata impattante', 'Bergamo, Canale Andreotti, 8', '-1', 'Voi giù roba carne tavola biondo pregare. Sperare arma filo legge promettere. Effetto segretario scegliere rompere alcuno voglia chiaro voi.', '2024-10-31', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Standardizzazione espansa reciproca', 'https://guariento.com/', '-1', 'Ordinare gioco annunciare. Sorridere accadere giù lira lei.
Conoscere restare gioco vasto chiaro. Qualcosa pronto verde sicuro in significare.', '2024-10-17', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Flessibilità riallineata nazionale', 'https://berengario.it/', '-1', 'Potere ritorno natura bene diverso avanzare dichiarare governo. Aprire mio entro luogo.', '2024-01-27', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Frame ergonomica euristica', 'http://pellico-poerio.org/', '-1', 'Avere sopra palazzo. Vestire fuggire divenire figura amare estremo attaccare. Affrontare stella gruppo lasciare capace gruppo cercare prima.', '2024-01-03', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Soluzione internet automatizzata incrementale', 'https://leblanc.com/', '-1', 'Riprendere peso distruggere punto subito su macchina. Portare pubblicare ricco ritornare ascoltare provincia vecchio. Cantare film corrente.', '2024-05-04', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura migliorata modulare', 'Rimini, Incrocio Argento, 95', '100', 'Ritenere pronto inutile montagna età giovane. Piazza stella regione ottenere.', '2024-03-14', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Migrazione universale scalabile', 'Brescia, Canale Tatiana, 7 Piano 1', '100', 'Anzi cioè preferire contare questo futuro comprendere. Pregare naturale albero ragione.
Rimettere ci sognare preparare qualsiasi russo mercato bellezza. Diretto sino estendere collo.', '2024-02-10', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Sinergia versatile eco-centrica', 'http://www.pavanello.com/', '-1', 'Mondo tecnico biondo vino secondo opinione scrivere. Domani spettacolo destino sino. Spiegare sposare porto mano scoprire nudo subito.', '2024-10-05', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Core organica non-volatile', 'Ferrara, Incrocio Errigo, 89 Piano 5', '250', 'Rispondere trarre suonare giro sottile ragione fiume. Cortile imporre caratteristico palazzo. Croce oh attento. Tono causa pubblicare lago nascere.', '2024-10-28', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Analizzatore estesa background', 'Salerno, Vicolo Mauro, 6 Piano 0', '200', 'Liberare proposta normale costituire avvocato. Parola attorno luna silenzio ci mostrare opinione apparire. Grosso uno discutere giocare stasera professore limite.', '2024-07-16', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Soluzione internet compatibile dinamica', 'https://tuzzolino-virgilio.com/', '-1', 'Mio fabbrica attendere inglese voltare divertire richiedere. Appunto necessità opera pietà valere avanzare ordine assumere. Lingua cioè esempio calcio studiare civile collo.', '2024-10-31', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Standardizzazione esclusiva asimmetrica', 'http://zampa.it/', '-1', 'Territorio qualche donna argomento risolvere. Amico concetto chissà vincere contare cambiare posare.', '2024-09-10', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Matrici robusta background', 'Modena, Vicolo Ruggeri, 53 Appartamento 5', '50', 'Anzi direttore attenzione. Salutare cercare storia nostro.
Vista grosso insomma spirito. Autorità compagnia esprimere semplice proprio politico peso.', '2024-05-28', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Metodologia proattiva uniforme', 'Modena, Piazza Spallanzani, 10', '250', 'Piccolo pensiero periodo. Inoltre esso musica oh mestiere terzo breve oggi.', '2024-03-16', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Proiezione multi-canale 24/7', 'Terni, Via Federigo, 164', '300', 'Prova disporre occhio libero armare. Perdere ieri scappare estendere intendere attraversare il offendere.', '2024-08-11', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Array sicura incrementale', 'Lecce, Contrada Giovanni, 43', '300', 'Via almeno offendere occorrere. Unire vero noi visita sotto campagna giustizia.
Dente pensare istante oggi. Anzi medio liberare chissà. Crescere pianura rispondere chiaro ecco produrre.', '2024-11-08', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Sito web progressiva modulare', 'Trento, Stretto Draghi, 48 Piano 5', '150', 'Crisi energia assoluto vino antico giungere. Militare abbandonare nord e domenica valere soldato.', '2024-10-03', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Codifica ottimizzata quinta generazione', 'https://www.nicolini.com/', '-1', 'Vivo pieno incontrare avvertire. Morte polizia qualsiasi intero dubbio. Forza valore infatti incontrare migliore.', '2024-06-05', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Software bilanciata coesiva', 'Cagliari, Incrocio Navarria, 85', '100', 'Dio giù tipo restare guardia bene concludere. Fiducia fondo vincere caro bastare appartenere. Religioso spazio notizia noto segretario.', '2024-05-25', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Definizione centralizzata tangibile', 'Parma, Incrocio Simone, 69 Appartamento 9', '300', 'Fiore estero politica sereno. Divertire potenza insegnare.
Impressione nobile pace. Diventare campagna unire attesa.', '2024-02-12', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Gerarchia polarizzata mission-critical', 'http://www.mezzetta-colletti.eu/', '-1', 'Uscire niente assistere crescere specie voltare ecco consentire. Assai bagno muovere età giardino assumere comprare. Mettere presidente tranquillo verso confronto eh.', '2024-02-21', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Matrice espansa sistemica', 'Prato, Stretto Foletti, 41 Piano 5', '100', 'Metà perfetto fretta verità pazzo metro tendere. Direttore provare folla o vita.
Dio signore linea territorio però. Notte autorità peso dunque comunicazione denaro.', '2024-08-31', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Attitudine riallineata dedicata', 'Latina, Contrada Concetta, 441 Appartamento 3', '100', 'Antico ritorno centrale parete industria aspettare. Attraversare misura via repubblica limitare crescere fantasia regione. Porto sorprendere moderno figurare simile religioso tu quarto.', '2024-10-17', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Utilizzazione versatile massimizzata', 'http://www.lupo.org/', '-1', 'Vuoto giudizio dunque unico pure cortile. Andare perciò tavola sopra cuore in argomento vendere. Compiere scrittore cristiano personale merito giustizia.', '2024-01-16', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Portale polarizzata motivazionale', 'Novara, Stretto Fo, 99 Appartamento 78', '200', 'Aiutare rappresentare lingua ciò partire. Perché posto segreto primo senza preciso.', '2024-10-12', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Supporto universale sistematica', 'Reggio Emilia, Contrada Pizzetti, 86 Piano 2', '200', 'Corpo egli infine commissione forza pena. Vista bello toccare cadere giudizio esporre. Matrimonio treno passione massimo produrre pericolo.
Fabbrica levare per porto ora.', '2024-02-16', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Software avanzata multi-tasking', 'https://deledda-tomasetti.it/', '-1', 'Epoca scoppiare politica lontano. Dire ordine russo quindi difficoltà. Finché ombra guidare.
Necessità pezzo piuttosto affermare riguardare. Addirittura volto esprimere età forma strano giornale.', '2024-11-04', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Successo implementata radicale', 'http://toso.it/', '-1', 'Straniero nazione stampa. Congresso superiore cattivo ricco consiglio atto offrire.
Odore isola prodotto nostro pregare rivelare. Metro realtà scherzare eppure.', '2024-02-12', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Intelligenza artificiale ottimizzata composita', 'Reggio Emilia, Borgo Gianpietro, 360 Piano 1', '-1', 'Autore sede impressione territorio contenere. Macchina vi entro mare assicurare porto pianura. Abitare soluzione breve cuore assumere salire.', '2024-08-02', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Soluzione internet bilanciata background', 'https://garrone.it/', '-1', 'Tu quadro preferire riprendere crisi pubblicare innamorare. Unico nave altro naturalmente personaggio roba. Vestire numeroso affare riva estero a.', '2024-03-19', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura condivisibile esecutiva', 'Sassari, Borgo Argentero, 35', '-1', 'Caldo erba ne sicurezza inoltre fiume. Tranquillo trarre risultare inverno limitare partito. Dipendere rapporto reale stato condizione scoppiare.', '2024-03-23', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura aperta sicura olistica', 'Cesena, Canale Sante, 93', '150', 'Lontano giusto amare innamorare internazionale prato papà politica. Vasto pericolo giugno spingere insegnare.', '2024-06-21', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Modello piccola mission-critical', 'Rimini, Strada Maria, 151 Piano 7', '-1', 'Resto uno temere aiuto. Sera difficoltà volta accogliere svolgere affermare presenza. Volgere accompagnare amore senso aiutare.', '2024-05-28', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Finestra temporale assimilata nazionale', 'https://zaccardo.it/', '-1', 'Svegliare casa distanza proposito vivo maniera. Attaccare opporre basso allontanare possibilità mezzo fissare. Tale bambino accettare evitare giudicare caffè forte prato.', '2024-05-19', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Parallelismo sincronizzata euristica', 'Bari, Canale Boiardo, 33', '-1', 'Facile straordinario fondo braccio uscire là dimostrare. Partire allontanare tavola memoria dinanzi regione richiedere.', '2024-06-28', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Funzione stand-alone basta sul contesto', 'Perugia, Rotonda Viridiana, 135 Appartamento 7', '-1', 'Strada mano rivolgere bravo discutere città. Civiltà chiedere territorio labbro difendere.
Ieri quanto amico milione fuori. Albergo tornare appartenere.', '2024-02-20', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('framework ergonomica basta sul contesto', 'Brescia, Stretto Chiara, 0', '100', 'Prato partito aprire azione impressione decidere. Aggiungere stabilire accadere quarto fronte sorprendere piangere. Sino riva finire interessare mamma.', '2024-07-05', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Matrici cross-platform biforcata', 'Andria, Via Donna, 9', '300', 'Americano pane uomo qui.
Impedire riconoscere piazza riva. Egli tutto colpire pranzo prezzo aspettare intero.', '2024-07-18', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Parallelismo totale discreta', 'Novara, Piazza Maurizio, 22', '250', 'Ministro bisognare accorgersi energia stella poiché dolore.', '2024-08-12', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Produttività stand-alone composita', 'Perugia, Viale Duodo, 64 Appartamento 60', '300', 'Tuo finché ambiente. Né attento interessante lei perdere idea.
Guidare commissione latino operazione compagnia partecipare chiamare. Niente baciare volere assistere.', '2024-06-29', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Matrici avanzata mission-critical', 'Sassari, Vicolo Cuzzocrea, 15', '200', 'Tardi ammettere abitare bambino. Costituire cambiare spingere internazionale tranquillo lanciare. Gusto cultura foglia favore allora.', '2024-07-06', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Access avanzata valore aggiunto', 'Reggio Calabria, Incrocio Ermes, 32', '100', 'Sapere fuggire creare difendere pazzo valere. Aggiungere su abito scherzare stella finire.', '2024-09-18', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Codifica migliorata direzionale', 'Bologna, Borgo Stefano, 1 Piano 2', '250', 'Senza passato territorio popolo questo espressione. Inutile classe basso puro proporre.', '2024-09-16', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Struttura di prezzo universale incrementale', 'https://www.boito.it/', '-1', 'Lago memoria tacere tono resto lato. Stesso coprire tu discutere io normale giù.
Frutto pensare dente automobile. Villa figlia lotta nuovo.', '2024-08-28', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Middleware integrata secondaria', 'Venezia, Stretto Giada, 962 Piano 2', '-1', 'Straniero anno triste sicuro estremo fiume risultato. Ogni occasione rimettere finché sogno trasformare accogliere. Parere tornare pregare voi salvare amico.', '2024-07-22', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Firmware intuitiva motivazionale', 'Milano, Borgo Marco, 310 Appartamento 8', '300', 'Entro scomparire voltare gamba. Operaio musica sorridere.
Grosso classe diventare contenere carne. Punta attore giardino posizione cattivo quello.', '2024-08-22', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Concetto polarizzata 24 ore', 'Siracusa, Viale Bassi, 380', '150', 'Subito esame stella oppure persona. Via scala o. Luce lanciare semplice medico contare.
Sì notare attesa matrimonio incontrare. Pronto maggio vero lago.', '2024-01-13', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Alleanza ottimizzata scalabile', 'Andria, Strada Lucciano, 237', '300', 'Egli civiltà cielo bocca oramai ministro. Fumare società cadere limite. Morte comodo stampa aggiungere servire costa.', '2024-08-03', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Approccio sinergica interattiva', 'https://marconi.com/', '-1', 'Meritare metro nascondere da nascere finalmente.
Compagno bianco alcuno notizia udire. Conseguenza opera quadro signore famiglia.', '2024-03-21', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Sfida universale nazionale', 'https://www.biagi-papetti.it/', '-1', 'Difficile sorriso conservare scendere comunque lingua. Serio unire disposizione labbro nobile viso internazionale. Collina maggiore sorgere e tornare articolo.', '2024-10-08', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Struttura di prezzo implementata nazionale', 'https://versace.org/', '-1', 'Stringere girare per. Assicurare procedere infatti niente. Volere occasione ieri potenza sociale.
Labbro comune chilometro pubblico rapporto donna compiere. Mattino pronto rendere divertire.', '2024-07-05', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Metodologia ridotta metodica', 'Vicenza, Viale Ornella, 888 Appartamento 0', '100', 'Necessario incontrare godere vestire limitare brutto. Casa epoca gioco dolce riprendere porre. Niente ritorno libro.', '2024-05-16', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Access bilanciata sesta generazione', 'Forlì, Viale Redi, 0', '50', 'Attraversare morale servire animo. Presto difendere chi per produrre.', '2024-05-29', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Moderazione sinergica regionale', 'Vicenza, Rotonda Spinelli, 27 Piano 5', '150', 'Nazionale abito immaginare oggetto maggio peggio. Verso stringere pelle lavorare. Cominciare messa attraversare distanza togliere.
Ragazzo villa incontrare stupido escludere. Fame sembrare dolce.', '2024-08-17', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Portale ottimizzata bi-direzionale', 'https://stein-villarosa.com/', '-1', 'Allora camminare titolo immagine collina raccontare verde. Tornare generale ieri diventare felice stringere.
Carattere domandare stamattina continuare. Fuoco popolazione subito amico nazionale punto.', '2024-07-08', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Iniziativa espansa quarta generazione', 'Perugia, Stretto Nino, 87', '100', 'Patria francese da madre popolo sentimento fissare. Pregare immaginare lingua brutto particolare. Uno interesse piangere cattolico quale intorno funzione.', '2024-02-24', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Forza lavoro multi-laterale terza generazione', 'Siracusa, Borgo Lamberto, 56 Appartamento 7', '300', 'Normale volgere tipo nulla difficile articolo. Don piano capo ne amare.
Attimo anno comune sguardo. Intero stare opporre spingere latino vestito dinanzi.', '2024-06-10', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Approccio programmabile asincrona', 'Brescia, Borgo Trillini, 17', '100', 'Voglia corsa per neppure paura attendere. Ammazzare brutto funzione materia.', '2024-01-25', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Hardware condivisibile locale', 'Siracusa, Contrada Serafina, 40 Piano 6', '150', 'Essa rosso esame mattino rivelare tipo. Cortile vivere ottenere largo piano. Richiedere contrario stasera madre comprare perché matrimonio.
Tardi polizia provvedere.', '2024-01-23', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Set di istruzioni ergonomica mobile', 'Firenze, Stretto Bertoli, 46 Appartamento 8', '100', 'Centrale termine mercato io. Sotto dubbio chiaro operaio provincia considerare distanza usare. Risolvere labbro usare pianura argomento prezzo pensiero.', '2024-10-27', '2');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Supporto multi-laterale modulare', 'Livorno, Vicolo Paltrinieri, 2', '-1', 'Contadino presenza motivo ciascuno. Periodo raggiungere continuo allora.
Fiume dire dimostrare nord caro presentare armare. Origine morire qui altro immagine salutare silenzio.', '2024-10-31', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Moratoria universale euristica', 'Cesena, Rotonda Silvia, 86 Appartamento 60', '100', 'Ogni esprimere spettacolo trascinare. Suo principio vicino fine madre stella innamorare.
Prezzo impedire italiano generale figurare finestra. Contatto scendere non giorno.', '2024-09-13', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura visionaria quinta generazione', 'Cagliari, Rotonda Niccolò, 42', '150', 'Condizione pesare preparare conseguenza rappresentare lo. Amare giungere condurre atto infatti corpo moderno nobile.', '2024-10-18', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Proiezione adattiva composita', 'https://scamarcio-ajello.eu/', '-1', 'Signorina invece tedesco sguardo attorno lavoro. Quasi entro distruggere parere badare regno temere. Dormire cambiare destro ordinare famiglia.', '2024-05-27', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Firmware distribuita esecutiva', 'Perugia, Contrada Rosalia, 72', '50', 'Rispetto colpa domenica davanti polizia potere richiedere titolo. Accettare addirittura lingua paura madre giorno almeno. Conservare da muovere volontà aggiungere.', '2024-07-02', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Approccio integrata responsiva', 'Siracusa, Borgo Gioffre, 487', '150', 'Comprendere tratto domani colpire presentare straniero desiderare. Segreto raccogliere mamma scherzare crisi nazionale. Caratteristico significare realtà vino conseguenza moglie mangiare oro.', '2024-05-05', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Protocollo progressiva discreta', 'https://cesaroni.it/', '-1', 'Specie società battaglia film evitare piede. Tranquillo compagnia contatto gioia.', '2024-02-28', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Archivio persistente statica', 'Messina, Stretto Maderno, 9', '-1', 'Calcio qualcuno voi più corpo luogo odore dinanzi. Ammettere conservare sottile resistere subito luna sorprendere formare. Filo stesso andare tagliare notevole.', '2024-03-23', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Strategia sincronizzata real-time', 'Venezia, Rotonda Berrè, 22 Piano 0', '200', 'Camminare dubbio mese atteggiamento giudicare. Buono età fretta fiducia improvviso seguito dovere.
Avvicinare fumare libertà.', '2024-08-29', '0');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Architettura aperta estesa modulare', 'Perugia, Rotonda Aporti, 6', '-1', 'Volta egli limite quarto oggi quanto ci mondo. Massimo successo mandare. Malattia girare guerra sforzo arte notevole.', '2024-11-05', '1');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Sovrastruttura virtuale valore aggiunto', 'Firenze, Viale Rocco, 988', '300', 'A concludere peggio. Volontà salutare pieno contenere senso latino utile fame. Insieme pesare si notte medio mangiare.', '2024-01-20', '3');
INSERT INTO evento (Nome, Luogo, NPosti, Descrizione, `Data`, Stato) VALUES ('Circuito organica nextgeneration', 'Messina, Borgo Rembrandt, 0 Appartamento 7', '100', 'Trasformare generale mattino cui. Arte qui diretto tavolo sacro pesare costa poiché. Ricordare produrre padrone magari ufficiale sorgere ragione chiedere.', '2024-04-16', '0');
