INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('177', '2023-12-20', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('135', '2014-12-25', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2021-02-26', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('207', '2012-03-31', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('199', '2015-05-26', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('65', '2011-03-16', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('117', '2014-12-19', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('197', '2015-11-18', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('78', '2014-04-06', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('152', '2016-02-03', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('204', '2019-08-14', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('29', '2014-02-19', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('54', '2022-02-01', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2016-11-01', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('173', '2009-11-13', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('67', '2016-07-24', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('16', '2011-02-19', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('94', '2013-03-13', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('192', '2018-12-05', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('126', '2014-04-24', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('13', '2018-06-01', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('71', '2010-08-08', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('25', '2016-04-09', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('146', '2020-04-13', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('160', '2020-01-30', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('145', '2016-06-22', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('28', '2015-07-06', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('53', '2016-11-26', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('72', '2021-06-11', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('4', '2020-03-08', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('136', '2015-09-08', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('74', '2011-02-12', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('106', '2024-09-21', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('218', '2017-03-26', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('132', '2022-02-15', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('43', '2019-09-16', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('46', '2017-03-06', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('208', '2013-11-13', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('187', '2023-04-28', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('98', '2012-05-29', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('45', '2017-04-06', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2015-07-01', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('148', '2022-05-25', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('93', '2020-09-04', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('46', '2013-05-04', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('64', '2017-11-04', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('54', '2017-04-05', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('15', '2014-11-27', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('94', '2018-04-03', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('96', '2019-02-27', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2022-10-19', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('140', '2016-03-03', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('87', '2018-01-15', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('149', '2013-04-16', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('47', '2010-01-10', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('131', '2020-11-04', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('77', '2015-12-17', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('41', '2012-01-03', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('34', '2011-11-11', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('47', '2020-09-29', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('38', '2023-07-18', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('178', '2023-03-03', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('56', '2023-03-17', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('68', '2019-10-25', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('97', '2019-06-20', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('6', '2018-05-28', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('7', '2015-07-02', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('136', '2017-11-03', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('177', '2015-07-09', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('153', '2023-07-10', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2022-04-04', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('64', '2023-08-25', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('2', '2022-03-16', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('147', '2015-11-18', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('22', '2020-11-05', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('180', '2011-12-12', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('158', '2014-09-15', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('140', '2023-03-14', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('3', '2015-02-17', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('71', '2023-03-25', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('148', '2021-11-11', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('147', '2015-09-30', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('96', '2015-11-13', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('215', '2017-01-29', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('123', '2022-06-08', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('61', '2016-06-26', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('34', '2013-12-14', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2024-10-12', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('157', '2018-07-10', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('71', '2023-10-01', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('66', '2011-04-23', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('18', '2013-07-21', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('87', '2022-11-13', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('212', '2019-07-24', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('12', '2017-04-19', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('183', '2017-09-25', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('178', '2020-06-15', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('141', '2013-03-17', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('83', '2010-05-28', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('103', '2012-10-04', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('131', '2023-08-10', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('178', '2020-08-17', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('159', '2017-02-02', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('80', '2013-01-14', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('36', '2018-01-17', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('213', '2021-11-12', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('56', '2024-04-12', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('103', '2023-05-10', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('124', '2023-06-03', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('209', '2017-11-14', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('106', '2017-06-07', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('27', '2022-03-23', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('82', '2023-02-19', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('183', '2014-02-15', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('196', '2016-02-24', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('67', '2012-02-28', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('2', '2023-11-16', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('125', '2021-11-23', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('59', '2010-04-26', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('146', '2023-01-08', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('50', '2016-03-18', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2019-02-11', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('169', '2012-06-30', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('39', '2013-01-03', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('3', '2014-02-10', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('173', '2019-10-25', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('197', '2015-05-14', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('102', '2011-12-24', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('12', '2011-07-02', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('29', '2010-08-17', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('205', '2013-06-11', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('30', '2011-02-24', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('108', '2019-08-02', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('66', '2013-01-25', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('174', '2019-12-04', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('11', '2014-12-11', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('56', '2023-05-19', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('75', '2017-08-13', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('208', '2019-11-25', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('13', '2011-03-10', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('138', '2020-05-26', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('10', '2011-05-24', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('38', '2012-05-24', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('87', '2016-04-16', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('121', '2015-06-06', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('23', '2013-12-10', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2018-07-07', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('66', '2024-03-01', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('199', '2015-01-01', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('86', '2013-12-24', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('156', '2020-09-22', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('153', '2013-12-12', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('127', '2018-01-26', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('55', '2011-03-14', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('154', '2013-10-30', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('67', '2020-11-20', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('199', '2013-02-12', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('45', '2015-04-16', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('62', '2011-10-16', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('175', '2012-03-20', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('182', '2013-11-01', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('77', '2013-09-01', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('128', '2022-12-20', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('84', '2023-04-22', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('160', '2015-05-21', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('99', '2013-01-16', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2016-02-19', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('82', '2023-12-23', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('219', '2024-01-21', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('37', '2011-09-18', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('195', '2015-04-12', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('211', '2018-10-03', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('189', '2010-01-17', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('120', '2021-03-21', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('152', '2015-03-23', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('59', '2011-05-10', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('196', '2020-01-10', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('53', '2012-06-07', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('175', '2013-04-18', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2012-01-24', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('168', '2020-05-12', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('34', '2015-02-17', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('136', '2017-11-22', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('67', '2021-09-04', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('23', '2020-11-28', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('194', '2009-11-21', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('29', '2010-01-14', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('156', '2022-08-09', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('204', '2018-01-12', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('30', '2022-03-22', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('131', '2020-05-19', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('138', '2016-11-27', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('86', '2017-01-20', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('114', '2019-12-25', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('27', '2022-02-26', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('146', '2012-04-29', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('104', '2020-05-20', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('141', '2021-12-13', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('133', '2012-02-19', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('57', '2018-01-10', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('211', '2022-07-11', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('26', '2015-01-28', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('79', '2022-03-02', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('158', '2020-07-01', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('176', '2024-06-15', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('4', '2010-08-19', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('1', '2022-04-08', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('133', '2021-01-25', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('177', '2015-05-05', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('22', '2009-10-28', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('131', '2022-02-19', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('76', '2016-02-11', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('112', '2009-09-23', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('80', '2019-06-14', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2011-07-28', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('74', '2022-08-27', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('112', '2019-04-30', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('196', '2010-11-29', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('166', '2013-08-02', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('78', '2017-05-07', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('11', '2023-06-13', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('54', '2021-02-04', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('26', '2018-06-16', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('136', '2020-04-01', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('192', '2019-07-25', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('44', '2023-01-17', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('140', '2013-05-24', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('41', '2018-11-03', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('42', '2015-01-24', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('26', '2023-11-18', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('168', '2013-03-23', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('64', '2012-08-08', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('11', '2011-06-29', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('181', '2012-07-18', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('16', '2022-04-04', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('207', '2013-01-14', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2020-09-29', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('214', '2021-07-21', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('75', '2010-04-30', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('78', '2018-08-25', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('183', '2017-05-21', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('8', '2021-01-29', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('107', '2013-02-16', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('107', '2017-08-19', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('7', '2016-02-27', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('25', '2018-10-14', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('207', '2010-07-10', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('68', '2022-05-20', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2020-06-04', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('59', '2010-01-29', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('51', '2011-06-09', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('199', '2023-09-02', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('183', '2024-03-30', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('203', '2009-09-16', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('136', '2019-06-28', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('161', '2014-05-15', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('26', '2020-05-29', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('157', '2022-07-20', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('54', '2010-11-01', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('118', '2016-02-02', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('65', '2016-01-13', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2011-07-25', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('140', '2012-11-25', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('81', '2013-08-09', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('87', '2023-04-24', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('121', '2021-10-20', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('59', '2015-02-02', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('203', '2023-10-16', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('31', '2014-03-23', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('202', '2013-09-27', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('43', '2018-04-15', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('101', '2018-01-19', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('194', '2018-07-17', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('161', '2011-11-08', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('120', '2022-12-24', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('14', '2009-12-23', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('211', '2023-06-03', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('100', '2023-10-16', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('127', '2009-09-11', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('105', '2012-07-16', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('121', '2009-11-09', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('31', '2019-12-14', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('143', '2013-12-02', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('100', '2016-03-20', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('19', '2015-04-08', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('197', '2017-12-31', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('98', '2017-09-08', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('126', '2020-03-30', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('68', '2018-11-24', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('79', '2015-12-24', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('218', '2024-07-09', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('163', '2017-05-19', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('73', '2021-03-12', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('22', '2010-07-10', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('85', '2017-01-12', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('166', '2015-07-13', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('214', '2016-08-10', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('6', '2022-03-04', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('71', '2018-02-24', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('208', '2019-03-31', 'Ha aggiornato le informazioni di pagamento');
