INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('43', '2014-03-04', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('103', '2012-02-06', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('90', '2013-10-12', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2009-10-21', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('81', '2024-08-17', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('166', '2015-11-23', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('193', '2014-03-24', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('175', '2023-07-03', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('157', '2021-07-10', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('67', '2018-08-15', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('111', '2024-05-12', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('154', '2014-05-18', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('89', '2018-12-07', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('57', '2010-06-14', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('137', '2019-10-21', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('213', '2021-08-28', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('143', '2012-08-08', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('99', '2011-01-23', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('117', '2013-05-19', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('43', '2024-10-04', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('104', '2024-10-26', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('221', '2020-03-05', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('113', '2010-04-24', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('66', '2012-07-24', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('214', '2019-01-11', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2019-06-06', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('182', '2017-02-19', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('116', '2010-11-01', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('171', '2012-04-30', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('187', '2023-10-05', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('98', '2009-10-28', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('105', '2015-02-19', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('170', '2022-06-11', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('68', '2023-01-07', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('80', '2023-07-11', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('213', '2021-06-20', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2012-06-24', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('69', '2020-11-28', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('165', '2017-10-05', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('38', '2017-09-04', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('74', '2015-11-21', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('14', '2016-12-28', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('109', '2022-10-02', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('4', '2023-10-30', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('43', '2014-08-04', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('5', '2022-06-12', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('85', '2016-08-21', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('193', '2017-02-10', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('125', '2012-02-26', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('198', '2018-02-05', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('2', '2021-11-18', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('185', '2012-07-23', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('181', '2023-07-26', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('203', '2012-07-28', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('127', '2018-04-01', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('187', '2023-08-26', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('5', '2020-06-18', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('56', '2023-11-16', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('92', '2018-10-15', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('172', '2009-11-03', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('100', '2024-08-11', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2021-11-17', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('216', '2016-01-10', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('216', '2022-11-14', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('100', '2018-08-24', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2024-08-07', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('212', '2015-12-23', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('19', '2018-03-09', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('6', '2015-02-24', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('206', '2012-07-11', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('137', '2013-08-31', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('199', '2016-01-18', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('107', '2019-05-21', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('116', '2021-02-21', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('150', '2020-01-24', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('93', '2013-12-31', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('3', '2018-12-17', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('218', '2013-07-18', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('52', '2020-11-15', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('5', '2013-03-04', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('99', '2023-03-04', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2016-06-23', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('52', '2018-09-03', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('52', '2017-03-04', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('181', '2010-09-07', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('119', '2022-04-16', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('210', '2024-04-13', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('130', '2012-05-30', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('127', '2012-04-26', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('185', '2023-03-17', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2010-12-31', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2011-03-30', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('5', '2019-05-17', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2020-06-04', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('22', '2018-10-10', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('167', '2022-03-31', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('66', '2021-03-30', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('182', '2018-07-01', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('40', '2015-07-03', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('109', '2021-04-22', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('118', '2013-12-23', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2013-07-31', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('100', '2023-11-23', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('157', '2012-12-03', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('52', '2024-05-04', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('206', '2023-02-21', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('59', '2018-06-02', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('34', '2015-08-31', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('92', '2022-06-26', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('25', '2015-03-21', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('28', '2012-04-26', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('69', '2010-03-03', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('101', '2009-10-06', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('128', '2018-02-13', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('16', '2014-12-25', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('95', '2021-01-21', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('15', '2018-11-30', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('187', '2011-02-05', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('197', '2015-07-11', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('135', '2018-02-17', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('50', '2015-11-15', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('125', '2019-11-09', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('33', '2011-07-14', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('57', '2022-10-11', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('139', '2015-01-28', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('10', '2011-11-03', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('160', '2019-06-20', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('41', '2010-03-19', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('195', '2013-04-16', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('138', '2018-12-24', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('153', '2019-12-27', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('74', '2022-04-05', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('6', '2017-12-18', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('175', '2013-06-02', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('199', '2011-09-22', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('36', '2019-06-04', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('49', '2011-05-30', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('172', '2011-08-15', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('101', '2013-07-02', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('82', '2017-09-06', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2013-11-12', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('112', '2009-12-31', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('116', '2019-04-15', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('12', '2010-06-03', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('35', '2015-02-16', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('89', '2019-01-02', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('121', '2017-08-15', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('198', '2024-09-18', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('194', '2014-02-19', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('51', '2012-02-13', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('54', '2014-10-22', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('212', '2011-07-14', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('196', '2023-09-26', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('151', '2016-02-06', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('82', '2016-09-18', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('4', '2024-10-30', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('174', '2022-11-10', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('29', '2018-06-22', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('85', '2014-01-21', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('143', '2024-10-01', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('162', '2017-02-23', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('110', '2011-08-07', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('63', '2018-03-01', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('170', '2009-12-04', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2023-07-17', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('25', '2014-10-05', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('84', '2021-02-08', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2020-10-28', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('184', '2022-09-15', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('3', '2016-04-10', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('204', '2024-07-28', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('95', '2011-11-21', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('205', '2024-10-26', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2024-10-11', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('23', '2018-07-11', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('214', '2012-11-26', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('100', '2022-03-06', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('185', '2018-09-19', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('5', '2019-07-15', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('208', '2022-03-22', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('122', '2022-12-02', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('218', '2014-02-02', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2022-04-19', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('114', '2010-02-19', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('141', '2023-04-07', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('10', '2018-03-15', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('45', '2014-10-31', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('84', '2022-02-26', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2021-04-17', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('96', '2017-01-27', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('115', '2022-04-30', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('29', '2014-03-18', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('60', '2010-01-13', 'Ha effettuato il login');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('15', '2017-02-07', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('19', '2013-01-30', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('215', '2019-07-13', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('172', '2020-06-28', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('175', '2024-09-11', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('173', '2023-10-27', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('83', '2013-11-21', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('195', '2024-01-09', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('154', '2015-02-25', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('45', '2024-01-24', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('179', '2016-07-02', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('47', '2018-07-26', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('118', '2014-09-06', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('78', '2019-07-26', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('28', '2014-10-11', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('154', '2023-01-01', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2019-10-04', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('153', '2018-10-15', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('71', '2017-12-11', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('81', '2021-10-04', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('185', '2013-12-23', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('16', '2013-10-16', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('3', '2021-03-05', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('184', '2021-08-19', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('63', '2024-08-28', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('141', '2018-05-22', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('83', '2010-03-29', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('196', '2016-11-02', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('195', '2020-05-23', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('219', '2018-05-18', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('177', '2024-03-21', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('182', '2019-04-05', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('113', '2023-04-02', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('80', '2015-01-28', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('27', '2011-11-11', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('206', '2018-08-11', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('98', '2022-03-19', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('110', '2024-03-29', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2016-06-25', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('217', '2012-04-29', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('149', '2009-11-02', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('200', '2022-07-21', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('211', '2016-01-29', 'Ha eliminato un account collegato');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('221', '2021-09-10', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('182', '2019-03-22', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('86', '2020-01-02', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('154', '2022-12-03', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('154', '2024-10-13', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('72', '2024-08-12', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('79', '2015-05-20', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('63', '2019-02-04', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('90', '2022-02-21', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('85', '2018-05-14', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('69', '2015-04-27', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('98', '2016-11-20', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('16', '2015-05-02', 'Ha reimpostato la password');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('120', '2019-10-08', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('1', '2022-01-11', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('198', '2020-08-25', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('111', '2011-03-12', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('16', '2022-07-23', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('24', '2017-09-07', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('46', '2021-01-30', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('220', '2023-01-10', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('114', '2011-11-27', 'Ha creato un nuovo evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('57', '2013-03-28', 'Ha visualizzato i dati del sensore');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('3', '2014-10-19', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('79', '2010-03-30', 'Ha modificato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('13', '2019-01-17', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('22', '2014-05-18', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('51', '2015-03-11', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('166', '2020-05-28', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('5', '2011-02-07', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('140', '2021-06-27', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('176', '2011-10-11', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('194', '2011-01-23', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('198', '2010-02-12', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('15', '2020-12-07', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('89', '2014-11-03', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('206', '2024-03-12', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('22', '2013-09-11', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('157', '2017-01-12', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('27', '2011-05-25', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('149', '2018-06-14', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('32', '2021-08-04', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('161', '2021-01-06', 'Ha aggiornato il profilo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('200', '2022-07-24', 'Ha inviato una segnalazione');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('90', '2019-02-03', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('82', '2017-06-10', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('208', '2013-12-21', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('137', '2010-06-04', 'Ha effettuato il sign up');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('33', '2017-04-13', 'Ha generato un report');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('31', '2019-05-21', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('191', '2013-12-22', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('91', '2010-10-16', 'Ha partecipato a un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('57', '2023-04-30', 'Ha modificato il logout');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('207', '2014-03-02', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('183', '2012-10-19', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('145', '2019-12-19', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('182', '2015-01-01', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('45', '2015-09-13', 'Ha cancellato un evento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('96', '2021-04-03', 'Ha cambiato l`email di contatto');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('23', '2024-10-19', 'Ha caricato un documento');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('115', '2020-03-29', 'Ha pubblicato un feedback');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('129', '2021-06-26', 'Ha effettuato il log out');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('142', '2015-08-28', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (, idUtente, `Data`, Descrizione) VALUES ('102', '2021-04-02', 'Ha inviato una segnalazione');
