INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('29', '1', '73', '2022-04-18', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('39', '2', '91', '2010-10-08', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('17', '3', '145', '2010-03-30', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '4', '74', '2015-07-07', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('15', '5', '80', '2010-01-16', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('22', '6', '27', '2013-07-09', 'Attorno rompere più loro.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('42', '7', '116', '2011-06-02', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('26', '8', '56', '2023-06-27', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('27', '9', '146', '2017-02-23', 'Braccio pronto vario antico.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '10', '184', '2020-10-05', 'Diverso società rendere.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '11', '114', '2013-08-29', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '12', '9', '2021-04-03', 'Frutto estero favore.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '13', '181', '2014-12-30', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '14', '84', '2018-08-04', 'Cielo pagare piangere.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '15', '196', '2024-09-12', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '16', '143', '2018-05-21', 'Mese autorità riva causa.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('28', '17', '105', '2024-02-07', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '18', '107', '2011-08-06', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '19', '117', '2024-05-28', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '20', '146', '2011-12-20', 'Centrale orecchio fondare.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '21', '173', '2010-05-10', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '22', '5', '2013-04-14', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('48', '23', '91', '2019-08-23', 'Peso gioia scendere impedire.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('38', '24', '156', '2012-08-22', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '25', '15', '2010-09-21', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '26', '179', '2014-10-28', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('3', '27', '141', '2015-05-28', 'Ritenere voce come.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('36', '28', '44', '2015-08-27', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('37', '29', '10', '2016-03-23', 'Sembrare cioè giù.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '30', '29', '2021-01-19', 'Marito sino sì segno uno.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '31', '47', '2015-02-03', 'Momento proposito tanto.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '32', '116', '2023-04-01', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '33', '200', '2012-05-24', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('28', '34', '189', '2017-03-10', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('17', '35', '40', '2011-01-04', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '36', '141', '2015-11-26', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('30', '37', '39', '2018-11-09', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('29', '38', '31', '2012-07-23', 'Ultimo opera produrre tavola.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '39', '104', '2011-01-19', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '40', '159', '2017-12-28', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('20', '41', '182', '2016-03-16', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('20', '42', '32', '2022-03-13', 'Rompere terreno sino senza.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('41', '43', '200', '2014-01-20', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('50', '44', '29', '2020-04-29', 'Mancare greco camminare.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('39', '45', '143', '2012-05-26', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '46', '24', '2016-06-27', 'Aiuto difendere essa conto.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('26', '47', '170', '2012-03-16', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('18', '48', '99', '2019-07-27', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '49', '39', '2010-10-11', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('19', '50', '83', '2017-07-06', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('32', '51', '32', '2011-12-29', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '52', '133', '2015-09-22', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('43', '53', '109', '2021-05-12', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('22', '54', '45', '2021-11-21', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '55', '9', '2013-10-27', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '56', '106', '2023-01-18', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('22', '57', '61', '2013-04-07', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '58', '72', '2014-09-21', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('31', '59', '176', '2009-09-04', 'Apparire ricordo meno.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('49', '60', '130', '2019-10-25', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('28', '61', '48', '2021-07-25', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '62', '18', '2022-02-06', 'Nome colore creare sviluppo.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('9', '63', '187', '2020-06-25', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('23', '64', '126', '2016-03-28', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('17', '65', '98', '2020-04-03', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('46', '66', '162', '2013-01-07', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('43', '67', '43', '2019-07-27', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('23', '68', '118', '2011-08-24', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('31', '69', '16', '2015-08-22', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('21', '70', '59', '2012-04-20', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('7', '71', '113', '2015-12-26', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '72', '196', '2015-01-14', 'Dedicare lago parlare.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('11', '73', '118', '2019-06-13', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('2', '74', '20', '2022-08-21', 'Fra quarto nord sedere lungo.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('35', '75', '177', '2010-08-27', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('46', '76', '134', '2016-07-31', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '77', '97', '2018-11-28', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '78', '170', '2020-09-21', 'Decidere escludere che acqua.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '79', '131', '2023-12-10', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('40', '80', '96', '2010-10-15', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('38', '81', '124', '2023-05-25', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('40', '82', '75', '2023-10-18', 'Qualcosa sangue base fede.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '83', '194', '2018-03-30', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('23', '84', '95', '2010-02-01', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('35', '85', '7', '2024-06-14', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('17', '86', '179', '2011-12-20', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('35', '87', '108', '2010-07-29', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('8', '88', '115', '2020-05-03', 'Comunque vino spingere medio.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('24', '89', '61', '2010-04-30', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('49', '90', '31', '2015-12-28', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('26', '91', '86', '2011-09-07', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '92', '181', '2012-09-10', 'Sicuro fretta civile.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('23', '93', '170', '2009-09-30', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('35', '94', '20', '2009-10-14', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('-1', '95', '35', '2016-04-07', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('13', '96', '94', '2014-09-01', '');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('11', '97', '83', '2011-01-21', 'Fratello chiave festa.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('23', '98', '145', '2013-03-25', 'Esso attento porta.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('8', '99', '53', '2018-01-29', 'Attenzione amare esso sacro.');
INSERT INTO partecipazione (idCitta, idEvento, idCittadino, DataPartecipazione, Segnalazione) VALUES ('13', '100', '20', '2016-07-23', 'Accanto vista pianura donna.');
