INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Biblioteca Centrale', 'Biblioteche');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Biblioteca per Ragazzi', 'Biblioteche');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Biblioteca di Quartiere', 'Biblioteche');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Parco Comunale', 'Parchi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Orto Botanico', 'Parchi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Giardino Pubblico', 'Parchi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Ospedale Generale', 'Ospedali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Clinica Comunale', 'Ospedali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro di Pronto Soccorso', 'Ospedali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Scuola Primaria', 'Scuole');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Scuola Media', 'Scuole');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Liceo Classico', 'Scuole');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Istituto Tecnico', 'Scuole');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro Sportivo Comunale', 'Centri Sportivi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Palestra Comunale', 'Centri Sportivi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Piscina Comunale', 'Centri Sportivi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Museo Civico', 'Musei');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Museo di Arte Moderna', 'Musei');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Museo Archeologico', 'Musei');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Teatro Comunale', 'Teatri');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Teatro dell`Opera', 'Teatri');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Auditorium Cittadino', 'Teatri');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Ufficio Postale Centrale', 'Uffici Postali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Ufficio Postale di Quartiere', 'Uffici Postali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Caserma dei Carabinieri', 'Stazioni di Servizio Pubblico');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Stazione dei Vigili del Fuoco', 'Stazioni di Servizio Pubblico');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Polizia Municipale', 'Stazioni di Servizio Pubblico');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro per l`Impiego', 'Centri per il Lavoro e i Servizi Sociali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro per gli Anziani', 'Centri per il Lavoro e i Servizi Sociali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Ufficio Servizi Sociali', 'Centri per il Lavoro e i Servizi Sociali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Anagrafe Comunale', 'Anagrafe e Servizi Comunali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Ufficio Protocollo', 'Anagrafe e Servizi Comunali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Ufficio Relazioni con il Pubblico', 'Anagrafe e Servizi Comunali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro Culturale', 'Centri Culturali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro Giovani', 'Centri Culturali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro Artistico', 'Centri Culturali');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Cimitero Comunale', 'Cimiteri');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Cimitero Monumentale', 'Cimiteri');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Sala Giochi Comunale', 'Centri Ricreativi');
INSERT INTO risorsapubblica (Nome, Tipo) VALUES ('Centro Ricreativo per Bambini', 'Centri Ricreativi');
