INSERT INTO feedback (Tipo) VALUES ('Positivo');
INSERT INTO feedback (Tipo) VALUES ('Negativo');
INSERT INTO feedback (Tipo) VALUES ('Neutro');
INSERT INTO feedback (Tipo) VALUES ('Suggerimento');
INSERT INTO feedback (Tipo) VALUES ('Lode');
INSERT INTO feedback (Tipo) VALUES ('Critica costruttiva');
INSERT INTO feedback (Tipo) VALUES ('Raccomandazione');
INSERT INTO feedback (Tipo) VALUES ('Problema tecnico');
INSERT INTO feedback (Tipo) VALUES ('Esperienza utente');
INSERT INTO feedback (Tipo) VALUES ('Qualità del servizio');
INSERT INTO feedback (Tipo) VALUES ('Tempistiche');
INSERT INTO feedback (Tipo) VALUES ('Comunicazione');
INSERT INTO feedback (Tipo) VALUES ('Soddisfazione generale');
INSERT INTO feedback (Tipo) VALUES ('Contenuto interessante');
INSERT INTO feedback (Tipo) VALUES ('Difficoltà nella fruizione');
INSERT INTO feedback (Tipo) VALUES ('Supporto clienti');
INSERT INTO feedback (Tipo) VALUES ('Facilità d`uso');
INSERT INTO feedback (Tipo) VALUES ('Qualità del prodotto');
INSERT INTO feedback (Tipo) VALUES ('Consigli');
INSERT INTO feedback (Tipo) VALUES ('Frustrazione');
