INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('138', '2018-11-29', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('154', '2020-12-30', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('211', '2019-09-27', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('112', '2016-02-25', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('129', '2018-01-24', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('119', '2017-10-04', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('164', '2010-01-02', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('147', '2023-08-27', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('201', '2014-09-05', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('126', '2010-01-12', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('140', '2024-11-28', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('102', '2012-07-19', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('196', '2015-03-08', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('191', '2010-09-27', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('120', '2024-08-23', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('49', '2024-09-16', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('47', '2023-10-30', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('176', '2017-03-16', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('220', '2012-11-04', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('108', '2019-07-05', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('10', '2019-01-11', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('158', '2013-06-27', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('9', '2022-08-22', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('33', '2016-03-18', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('11', '2018-06-10', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('85', '2021-04-11', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('113', '2019-12-22', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('119', '2013-03-28', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('195', '2018-11-20', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('211', '2016-09-28', 'Ha pubblicato un feedback');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('78', '2024-10-07', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('179', '2015-02-10', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('20', '2018-06-13', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('122', '2024-09-19', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('213', '2013-04-28', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('4', '2018-04-02', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('179', '2016-01-05', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('214', '2024-11-28', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('44', '2024-01-14', 'Ha modificato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('144', '2015-09-28', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('5', '2021-07-08', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('130', '2024-08-14', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('54', '2010-11-03', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('105', '2013-08-10', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('18', '2011-12-14', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('179', '2015-12-29', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('221', '2018-12-31', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('174', '2018-11-07', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('41', '2023-12-08', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('136', '2017-03-14', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('97', '2022-09-08', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('72', '2021-06-05', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('79', '2014-03-11', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('160', '2019-03-02', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('52', '2010-11-27', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('190', '2012-09-02', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('114', '2009-11-10', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('173', '2010-09-25', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('33', '2023-07-23', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('179', '2015-11-13', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('162', '2022-12-07', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('178', '2020-12-30', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('58', '2021-01-31', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('41', '2018-02-26', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('214', '2018-03-11', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('15', '2018-05-01', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('185', '2011-03-11', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('206', '2016-10-13', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('14', '2010-02-27', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('114', '2013-09-13', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('138', '2020-10-08', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('39', '2015-06-08', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('204', '2010-04-05', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('81', '2019-03-19', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('43', '2016-08-17', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('176', '2017-03-07', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('106', '2021-07-01', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('127', '2021-09-16', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('165', '2017-06-17', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('45', '2015-02-15', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('25', '2021-08-31', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('106', '2013-01-18', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('161', '2012-12-31', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('213', '2017-05-12', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('183', '2016-06-11', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('189', '2014-04-09', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('175', '2021-09-18', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('130', '2016-11-01', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('191', '2024-09-29', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('173', '2012-09-17', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('115', '2021-06-13', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('220', '2019-07-27', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('166', '2019-09-16', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('180', '2012-04-20', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('104', '2015-09-14', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('94', '2015-02-11', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('161', '2018-05-31', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('26', '2012-03-02', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('103', '2018-04-16', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('74', '2018-01-17', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('108', '2022-05-18', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('205', '2018-10-13', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('196', '2020-12-30', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('8', '2012-11-24', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('140', '2019-08-27', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('183', '2018-05-29', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('114', '2014-06-07', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('32', '2013-04-01', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('194', '2011-11-07', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('69', '2020-12-03', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('28', '2021-02-04', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('153', '2014-01-01', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('98', '2023-01-14', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('180', '2024-09-18', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('46', '2020-09-25', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('183', '2011-03-29', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('57', '2013-08-19', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('162', '2010-01-04', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('67', '2018-07-10', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('82', '2023-08-29', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('148', '2010-09-02', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('53', '2013-04-04', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('127', '2015-03-14', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('9', '2010-03-29', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('8', '2013-06-26', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('209', '2017-08-09', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('197', '2018-04-11', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('212', '2021-03-27', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('127', '2021-10-29', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('156', '2010-11-21', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('65', '2024-09-04', 'Ha modificato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('187', '2023-10-07', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('142', '2019-08-30', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('62', '2023-10-31', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('104', '2023-02-07', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('40', '2021-10-23', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('221', '2020-05-03', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('221', '2022-02-12', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('53', '2020-08-04', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('191', '2012-01-25', 'Ha pubblicato un feedback');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('209', '2011-09-21', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('185', '2021-10-20', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('138', '2022-11-11', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('145', '2010-03-18', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('81', '2012-12-23', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('58', '2023-04-27', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('181', '2010-02-03', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('162', '2010-05-20', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('54', '2012-08-08', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('220', '2023-06-12', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('7', '2018-06-03', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('220', '2020-12-27', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('133', '2018-10-25', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('77', '2021-03-03', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('191', '2021-02-20', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('168', '2017-02-06', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('65', '2012-12-23', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('33', '2012-01-12', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('76', '2016-12-04', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('180', '2009-10-27', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('219', '2009-11-08', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('31', '2020-02-02', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('123', '2016-10-01', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('130', '2010-04-04', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('89', '2011-05-14', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('115', '2009-10-16', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('78', '2013-08-06', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('77', '2020-01-24', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('103', '2014-07-01', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('45', '2014-01-11', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('52', '2010-08-18', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('191', '2010-05-09', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('35', '2012-07-20', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('170', '2024-10-16', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('77', '2010-08-08', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('92', '2010-07-17', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('215', '2022-04-04', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('19', '2010-05-05', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('89', '2019-05-02', 'Ha aggiornato le informazioni di pagamento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('98', '2020-02-04', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('219', '2023-07-13', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('62', '2018-07-19', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('32', '2012-10-17', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('187', '2011-04-19', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('189', '2019-12-28', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('92', '2016-09-23', 'Ha pubblicato un feedback');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('149', '2016-03-19', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('163', '2015-08-03', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('166', '2022-04-05', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('168', '2022-12-18', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('171', '2019-10-20', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('144', '2020-05-03', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('135', '2011-04-21', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('145', '2010-07-16', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('134', '2024-02-07', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('162', '2024-09-03', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('201', '2010-10-21', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('111', '2022-10-29', 'Ha pubblicato un feedback');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('160', '2023-08-05', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('220', '2017-02-11', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('205', '2022-03-10', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('129', '2023-05-18', 'Ha modificato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('110', '2015-12-24', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('50', '2018-12-27', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('107', '2012-11-01', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('210', '2021-03-21', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('203', '2012-03-23', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('113', '2013-06-05', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('121', '2024-08-17', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('213', '2009-10-22', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('187', '2009-12-24', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('211', '2021-02-13', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('209', '2012-02-08', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('9', '2015-09-01', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('184', '2011-09-21', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('163', '2018-09-20', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('135', '2023-09-07', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('183', '2018-03-08', 'Ha modificato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('16', '2018-08-12', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('94', '2010-07-19', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('40', '2011-08-04', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('193', '2022-08-24', 'Ha modificato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('46', '2020-12-15', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('150', '2012-08-12', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('181', '2021-02-13', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('99', '2018-07-03', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('62', '2018-04-28', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('174', '2021-02-23', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('135', '2011-11-20', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('210', '2014-12-17', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('18', '2017-04-23', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('60', '2017-01-12', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('107', '2012-05-28', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('103', '2012-06-18', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('58', '2016-12-15', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('66', '2023-01-05', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('139', '2018-06-11', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('54', '2014-09-23', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('16', '2023-06-13', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('74', '2011-07-28', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('90', '2013-09-20', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('197', '2022-03-14', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('176', '2024-08-11', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('77', '2020-03-18', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('185', '2016-10-29', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('29', '2024-11-21', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('136', '2021-09-02', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('97', '2009-10-21', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('35', '2019-07-31', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('115', '2010-05-21', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('221', '2024-06-22', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('69', '2013-02-09', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('29', '2012-10-05', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('197', '2010-12-23', 'Ha pubblicato un feedback');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('170', '2019-05-14', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('203', '2011-09-08', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('167', '2019-02-02', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('50', '2018-05-07', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('18', '2020-06-13', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('52', '2024-05-13', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('182', '2010-06-05', 'Ha consultato il bilancio delle spese pubbliche');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('181', '2023-09-28', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('133', '2021-01-19', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('72', '2010-11-07', 'Ha caricato un documento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('157', '2018-08-25', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('89', '2020-07-19', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('162', '2020-10-27', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('205', '2016-07-02', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('181', '2020-02-10', 'Ha pubblicato un feedback');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('153', '2015-03-19', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('197', '2021-01-30', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('34', '2024-05-07', 'Ha effettuato il log out');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('57', '2011-04-03', 'Ha visualizzato una risorsa pubblica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('19', '2009-09-23', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('74', '2010-05-02', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('134', '2012-04-28', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('129', '2017-03-03', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('24', '2019-01-25', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('29', '2009-11-01', 'Ha effettuato il sign up');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('22', '2023-10-08', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('184', '2023-03-21', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('140', '2013-08-03', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('161', '2021-10-01', 'Ha creato un nuovo evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('135', '2014-07-15', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('132', '2020-10-10', 'Ha partecipato a un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('34', '2023-10-28', 'Ha aggiornato il profilo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('74', '2022-08-13', 'Ha modificato il logout');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('78', '2018-10-31', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('31', '2015-04-07', 'Ha aggiornato le preferenze di notifica');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('119', '2014-08-16', 'Ha cambiato l`email di contatto');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('97', '2021-05-24', 'Ha reimpostato la password');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('162', '2015-10-11', 'Ha inviato una segnalazione');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('177', '2018-07-14', 'Ha aggiornato le impostazioni dell`account');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('155', '2015-10-14', 'Ha generato un report');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('188', '2021-06-29', 'Ha visualizzato i dati del sensore');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('157', '2023-09-02', 'Ha eliminato un account collegato');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('169', '2020-08-11', 'Ha effettuato il login');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('135', '2018-05-15', 'Ha effettuato un cambio di ruolo');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('203', '2010-01-05', 'Ha cancellato un evento');
INSERT INTO log (idUtente, `Data`, Descrizione) VALUES ('104', '2009-12-19', 'Ha effettuato un cambio di ruolo');
